name: ExtraHardMode
main: com.extrahardmode.ExtraHardMode
version: 3.6.6
description: Add new challenges to minecraft
dev-url: http://dev.bukkit.org/bukkit-plugins/fun-hard-mode/
#project lead
author: Diemex
authors: [Mitsugaru, bigscary]
#ensure that we are loaded after multiworld plugins
softdepend: [Multiverse-Core, My Worlds, MystCraft, Transporter, WorldGuard, Prism, LogBlock, CoreProtect, HawkEye]
commands:
    ehm:
        description: Root command for ExtraHardMode
        usage: /ehm - Show the main menu
    ehm reload:
        description: Reload the configuration and modules
        usage: /ehm reload
    ehm version:
        description: Shows the version and build number
        usage: /ehm version
    ehm enabled:
        description: Tells you if ExtraHardMode is enabled in the world
        usage: /ehm enabled [world]
permissions:
    ExtraHardMode.*:
        description: Grant ALL the permission nodes
        default: no
        children:
           ExtraHardMode.admin: true
           ExtraHardMode.bypass: true
           ExtraHardMode.silent.stone_mining_help: true
           ExtraHardMode.silent.no_placing_ore_against_stone: true
           ExtraHardMode.silent.realistic_building: true
           ExtraHardMode.silent.limited_torch_placement: true
           ExtraHardMode.silent.no_torches_here: true
    ExtraHardMode.admin:
        description: Grants user ability to administrate the plugin.
        default: op
    ExtraHardMode.bypass.*:
        description: Grants bypass permission for some extra hard mode rules.
        default: no
        children:
           ExtraHardMode.bypass.creepers: true
           ExtraHardMode.bypass.bypass: true
           ExtraHardMode.bypass.inventory: true
    ExtraHardMode.bypass.bypass:
        description: Old permission that will be replaced by subpermissions
        default: no
    ExtraHardMode.bypass.creepers:
        description: Player with this permission will bypass all creeper features, but the flaming creepers
        default: no
    ExtraHardMode.bypass.inventory:
        description: Player with this permission will not lose additional inventory on death
        default: no
    ExtraHardMode.silent.*:
        description: Grants ALL silent permission nodes
        default: no
        children:
           ExtraHardMode.silent.stone_mining_help: true
           ExtraHardMode.silent.no_placing_ore_against_stone: true
           ExtraHardMode.silent.realistic_building: true
           ExtraHardMode.silent.limited_torch_placement: true
           ExtraHardMode.silent.no_torches_here: true
    ExtraHardMode.silent.stone_mining_help:
        description: hides the stone mining help message
        default: no
    ExtraHardMode.silent.no_placing_ore_against_stone:
        description: hides the no placing ore against stone message
        default: no
    ExtraHardMode.silent.realistic_building:
        description: hides the realistic building message
        default: no
    ExtraHardMode.silent.limited_torch_placement:
        description: hides the limited torch placement message
        default: no
    ExtraHardMode.silent.no_torches_here:
        description: hides the no torches here message
        default: no